# Generated by Django 4.1.5 on 2023-02-04 18:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thedar', '0002_alter_post_checkin_alter_post_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='report',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
