# Generated by Django 4.1.5 on 2023-02-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedar', '0003_alter_post_details_alter_post_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
