# Generated by Django 4.1.5 on 2023-02-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thedar', '0004_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='report_image',
        ),
    ]
