# Generated by Django 4.1.5 on 2023-02-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedar', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
