# Generated by Django 4.1.7 on 2023-03-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedar', '0007_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='position',
            field=models.CharField(choices=[('Lobby 1', 'Lobby 1'), ('Lobby 2', 'Lobby 2'), ('Loading dock', 'Loading dock'), ('Patrol 1', 'Patrol 1'), ('Patrol 2', 'Patrol 2')], max_length=200),
        ),
    ]
